# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-26 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170922_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='User',
            new_name='user',
        ),
    ]
