# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20170926_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='User',
            new_name='user',
        ),
    ]
