# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20170927_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='detail',
            field=models.CharField(default=b'', max_length=150),
        ),
        migrations.AddField(
            model_name='address',
            name='zipCode',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='phoneNumber',
            field=models.CharField(default=b'888888888', max_length=15),
        ),
    ]
