# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20171003_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
