# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20171004_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
