# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_item_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
