# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_paymentmethod_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='city',
            field=models.CharField(default='Bogotá', max_length=150),
        ),
        migrations.AddField(
            model_name='producer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='image',
            field=models.CharField(default='https://definicion.mx/wp-content/uploads/2013/11/usuario.jpg', max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='phoneNumber',
            field=models.CharField(default='888888888', max_length=15),
        ),
    ]
