# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-14 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_auto_20171013_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='typeIdentification',
            field=models.CharField(default='Cedula de Ciudadanía', max_length=150),
        ),
    ]
