# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-15 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_producer_typeidentification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hello.ShoppingCart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hello.ShoppingCart'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='hello.Category'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='createdDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
