# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-15 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20171015_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsperbasket',
            name='item',
        ),
        migrations.AddField(
            model_name='itemsperbasket',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hello.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsperbasket',
            name='quantity',
            field=models.FloatField(default=None),
        ),
    ]
