# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-16 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20171016_0039'),
        ('hello', '0015_auto_20171015_1134'),
    ]

    operations = [
    ]
