# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-04 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_auto_20171102_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
