# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-09 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_auto_20171109_1248'),
        ('hello', '0018_order_deliveryaddress'),
    ]

    operations = [
    ]
