# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_auto_20171115_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.Product'),
            preserve_default=False,
        ),
    ]
