# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-28 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_auto_20171115_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Producer'),
        ),
    ]
