# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-29 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_basket_product'),
        ('hello', '0021_auto_20171128_1419'),
    ]

    operations = [
    ]
